# Generated by Django 3.0.3 on 2020-03-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=500, unique=True)),
                ('avatar', models.ImageField(upload_to='avatar/')),
                ('location', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
