# Generated by Django 3.0.3 on 2020-04-11 09:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('content', models.TextField(max_length=250)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('ending_at', models.DateTimeField(default=datetime.datetime(2020, 5, 11, 9, 46, 54, 622597))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'open'), (1, 'pending'), (2, 'closed')], default=0)),
                ('type', models.CharField(choices=[('WANT', 'wanted'), ('OFFER', 'offered')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_notices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
