# Generated by Django 3.0.3 on 2020-04-08 12:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('type', models.IntegerField(choices=[(0, 'WANTED'), (1, 'OFFERED')])),
                ('content', models.TextField(max_length=250)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('ending_at', models.DateTimeField(default=datetime.datetime(2020, 5, 8, 12, 26, 8, 800464))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'OPEN'), (1, 'PENDING'), (2, 'CLOSED')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
