# Generated by Django 3.0.3 on 2020-04-11 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpnotice',
            name='ending_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 9, 46, 56, 446499)),
        ),
    ]
