# Generated by Django 3.0.3 on 2020-04-11 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpme', '0002_auto_20200411_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpnotice',
            name='ending_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 11, 3, 11, 830521)),
        ),
    ]
